import {Product} from '../types';
import {LocalRootState} from '../state/reducers';

export const mockReduxStore: LocalRootState = {
    admin: {
        newsletterSignups: [],
        isLoading: false,
        error: null,
        isDeleted: false,
        isUploaded: false,
        isUpdating: false,
        isUpdated: false,
        isCreated: false,
        clients: [
            {
                _id: '123',
                email: 'test@gmail.com',
                name: 'john',
                password: '12345',
                role: 'user',
                avatar: {url: 'test.jpg', public_id: 'testID'},
            },
        ],
    },
    products: {
        products: [
            {
                department: 'men',
                isFeatured: true,
                colors: ['Pearl', 'White', ''],
                size: ['10.5'],
                _id: '60ec4b0d182a728b9d356c34',
                brand: 'Air Jordan',
                description:
                    'In 1992, Michael Jordan laced up his Air Jordan VII sneakers to win a 2nd consecutive NBA Championship, and a gold medal with the \'Dream Team\' in the Olympic Games. For this Air Jordan, Tinker Hatfield drew inspiration from West African tribal art and created a unique design. But the Air Jordan VII isn\'t just looks, this sneaker was also applauded for comfort on the court due to its neoprene sockliner, which provides a snug fit.',
                images: [
                    {
                        _id: '60ec4b0d182a728b9d356c35',
                        public_id: 'street-trend/products/cummusiuf80rolweuzjs',
                        url: '/public/images/990v6_1.webp',
                    },
                ],
                model: 'VII (7) Retro',
                price: 399,
                styleCode: '304775-281',
            },

            {
                department: 'men',
                isFeatured: false,
                colors: ['Orange', 'Black', 'White'],
                size: ['11'],
                _id: '60ed77e0f236a82619a80034',
                brand: 'Adidas',
                description:
                    'Boasting a design inspired by several classic Adidas models (Micro Pacer, Rising Star, and Boston Super), the Adidas NMD Runner is an ultra comfortable sneaker with a contemporary design. They are crafted with a breathable and flexible Primeknit upper, energy-returning Boost technology, leather heel badge, bootie construction, and a webbed rubber outsole.',
                images: [
                    {
                        _id: '60ed784ef236a82619a8003a',
                        public_id: 'street-trend/products/ffsscrm5ghlruvyugkdy',
                        url: '/public/images/990v6_1.webp',
                    },
                ],
                model: 'NMD_R1',
                price: 140,
                styleCode: 'ac8171',
            },
            {
                department: 'men',
                isFeatured: true,
                colors: ['Black'],
                size: ['11'],
                _id: '60edd01c01d3ca10f5eafa49',
                brand: 'Adidas',
                description:
                    'Developed by Kanye West, the Adidas Yeezy 500 is a sporty and stylish model. They are crafted with a combination of premium suede, leather, and mesh, feature an adiPRENE sole, piping details, pull tab, and a rubber outsole.',
                images: [
                    {
                        _id: '60edd01c01d3ca10f5eafa4a',
                        public_id: 'street-trend/products/xmh4goid166sizjv83b1',
                        url: '/public/images/990v6_1.webp',
                    },
                    {
                        _id: '60edd01c01d3ca10f5eafa4b',
                        public_id: 'street-trend/products/ofml12qnkwlrdvlofwl5',
                        url: '/a18alfred/image/upload/v1626198038/street-trend/products/ofml12qnkwlrdvlofwl5.png',
                    },
                    {
                        _id: '60edd01c01d3ca10f5eafa4c',
                        public_id: 'street-trend/products/rr3ivdk0o7vvwd1qb1wg',
                        url: '/a18alfred/image/upload/v1626198041/street-trend/products/rr3ivdk0o7vvwd1qb1wg.png',
                    },
                    {
                        _id: '60edd01c01d3ca10f5eafa4d',
                        public_id: 'street-trend/products/thypql9jsyvgyie0qglr',
                        url: '/a18alfred/image/upload/v1626198043/street-trend/products/thypql9jsyvgyie0qglr.png',
                    },
                ],
                model: 'Yeezy 500',
                price: 550,
                styleCode: 'f36640',
            },
        ],
        product: {
            department: 'men',
            isFeatured: true,
            colors: ['White', 'Black'],
            size: ['7.5'],
            _id: '60ec4beb182a728b9d356c44',
            brand: 'Nike',
            description: 'Nike Air Vapormax Plus',
            images: [
                {
                    _id: '60ec4beb182a728b9d356c45',
                    public_id: 'street-trend/products/cljhv7wwz3va5rg5pilr',
                    url: '/a18alfred/image/upload/v1626098663/street-trend/products/cljhv7wwz3va5rg5pilr.png',
                },
                {
                    _id: '60ec4beb182a728b9d356c46',
                    public_id: 'street-trend/products/cr1ter0wc7y4mtzjli8z',
                    url: '/a18alfred/image/upload/v1626098666/street-trend/products/cr1ter0wc7y4mtzjli8z.png',
                },
            ],
            model: 'Air Vapormax Plus',
            price: 270,
            styleCode: 'mss-cw6974100',
        },
        filters: {
            brand: '',
            color: '',
            size: '',
            department: '',
        },
        filteredProducts: [
            {
                department: 'men',
                isFeatured: true,
                colors: ['Pearl', 'White', ''],
                size: ['10.5'],
                _id: '60ec4b0d182a728b9d356c34',
                brand: 'Air Jordan',
                description:
                    'In 1992, Michael Jordan laced up his Air Jordan VII sneakers to win a 2nd consecutive NBA Championship, and a gold medal with the \'Dream Team\' in the Olympic Games. For this Air Jordan, Tinker Hatfield drew inspiration from West African tribal art and created a unique design. But the Air Jordan VII isn\'t just looks, this sneaker was also applauded for comfort on the court due to its neoprene sockliner, which provides a snug fit.',
                images: [
                    {
                        _id: '60ec4b0d182a728b9d356c35',
                        public_id: 'street-trend/products/cummusiuf80rolweuzjs',
                        url: '/a18alfred/image/upload/v1626098444/street-trend/products/cummusiuf80rolweuzjs.png',
                    },
                ],
                model: 'VII (7) Retro',
                price: 399,
                styleCode: '304775-281',
            },
        ],
        isLoading: false,
        error: null,
    },
    ui: {
        isModalOpen: false,
        modalYposition: 0,
        modalContent: null,
        theme: 'dark',
    },
    auth: {
        user: null,
        isLoading: false,
        isAuthenticated: false,
        isRegistered: false,
        success: false,
        error: null,
        isUpdated: false,
    },
    cart: {
        cart: [],
        discount: 0,
        total: 0,
        productAmount: 0,
    },
    recentlyViewed: {
        viewedProducts: [
            {
                department: 'men',
                colors: ['Pearl', 'White', ''],
                isFeatured: true,
                size: ['10.5'],
                _id: '60ec4b0d182a728b9d356c34',
                brand: 'Air Jordan',
                description:
                    'In 1992, Michael Jordan laced up his Air Jordan VII sneakers to win a 2nd consecutive NBA Championship, and a gold medal with the \'Dream Team\' in the Olympic Games. For this Air Jordan, Tinker Hatfield drew inspiration from West African tribal art and created a unique design. But the Air Jordan VII isn\'t just looks, this sneaker was also applauded for comfort on the court due to its neoprene sockliner, which provides a snug fit.',
                images: [
                    {
                        _id: '60ec4b0d182a728b9d356c35',
                        public_id: 'street-trend/products/cummusiuf80rolweuzjs',
                        url: '/public/images/990v6_1.webp',
                    },
                ],
                model: 'VII (7) Retro',
                price: 399,
                styleCode: '304775-281',
            },
        ],
        isLoading: false,
    },

    checkout: {
        isLoading: false,
        userShippingInfo: null,
        shippingMethod: 'free',
        isShippingInfoCollected: false,
        isShippingMethodSelected: false,
        isPaymentInfoCollected: false,
        error: null,
        isPaid: false,
    },
    orders: {
        orders: [
            {
                shippingInfo: {
                    firstName: 'Alfred',
                    lastName: 'Mirzasalikhov',
                    email: 'a18alfred@yandex.com',
                    city: 'Las Vegas',
                    address: '3001 Lake East Dr., Apt. 2024',
                    country: 'USA',
                    state: 'Las Vegas',
                    zipCode: '89117',
                    phone: '7022515588',
                },
                paymentInfo: {
                    paymentID: 'test123',
                    status: 'Processed/Paid',
                },
                deliveryStatus: 'Not delivered',
                _id: '60fd5aecc3eae1efef789371',
                user: '60f1cf2b87c05534ca22d76f',
                orderTotal: 850,
                purchase: [
                    {
                        productID: '60eee5c7f6551d566f992501',
                        brand: 'New Balance',
                        model: '990v6',
                        size: '10.5',
                        img: 'https://res.cloudinary.com/dvoz1ragp/image/upload/v1685824429/street-trend/products/xuuukwjb7j8c7ipm6xaz.webp',
                        price: 300,
                    },
                    {
                        productID: '60edd01c01d3ca10f5eafa49',
                        brand: 'Puma',
                        model: 'Yeezy 500',
                        size: '11',
                        img: 'https://res.cloudinary.com/dvoz1ragp/image/upload/v1685824429/street-trend/products/xuuukwjb7j8c7ipm6xaz.webp',
                        price: 550,
                    },
                ],
                paidAt: '2021-07-25T12:37:00.294Z',
            },
            {
                shippingInfo: {
                    firstName: 'Alfred',
                    lastName: 'Mirzasalikhov',
                    email: 'a18alfred@yandex.com',
                    city: 'Las Vegas',
                    address: '3001 Lake East Dr., Apt. 2024',
                    country: 'USA',
                    state: 'Las Vegas',
                    zipCode: '89117',
                    phone: '7022515588',
                },
                paymentInfo: {
                    paymentID: 'test123',
                    status: 'Processed/Paid',
                },
                deliveryStatus: 'Not delivered',
                _id: '60fd8c6397efed0e6dfa5f0d',
                user: '60f1cf2b87c05534ca22d76f',
                orderTotal: 2719,
                purchase: [
                    {
                        productID: '60eee5c7f6551d566f992501',
                        brand: 'New Balance',
                        model: 'Yeezy 500 (Enflame)',
                        size: '10.5',
                        img: 'https://res.cloudinary.com/dvoz1ragp/image/upload/v1685824429/street-trend/products/xuuukwjb7j8c7ipm6xaz.webp',
                        price: 300,
                    },
                    {
                        productID: '60edd01c01d3ca10f5eafa49',
                        brand: 'New Balance',
                        model: 'Yeezy 500',
                        size: '11',
                        img: 'https://res.cloudinary.com/dvoz1ragp/image/upload/v1685824429/street-trend/products/xuuukwjb7j8c7ipm6xaz.webp',
                        price: 550,
                    },
                    {
                        productID: '60ec87e907700a3bef404d32',
                        brand: 'New Balance',
                        model: 'OG Travis Scott',
                        size: '11',
                        img: 'https://res.cloudinary.com/dvoz1ragp/image/upload/v1685824429/street-trend/products/xuuukwjb7j8c7ipm6xaz.webp',
                        price: 1200,
                    },
                    {
                        productID: '60ec4beb182a728b9d356c44',
                        brand: 'New Balance',
                        model: 'Air Vapormax Plus',
                        size: '7.5',
                        img: 'https://res.cloudinary.com/dvoz1ragp/image/upload/v1685824429/street-trend/products/xuuukwjb7j8c7ipm6xaz.webp',
                        price: 270,
                    },
                    {
                        productID: '60ec4b0d182a728b9d356c34',
                        brand: 'Air Jordan',
                        model: 'VII (7) Retro',
                        size: '10.5',
                        img: 'https://res.cloudinary.com/dvoz1ragp/image/upload/v1685824429/street-trend/products/xuuukwjb7j8c7ipm6xaz.webp',
                        price: 399,
                    },
                ],
                paidAt: '2021-07-25T16:08:03.638Z',
            },
            {
                shippingInfo: {
                    firstName: 'Cathleen',
                    lastName: 'Goodman',
                    email: 'a18alfred1989@gmail.com',
                    city: 'Occaecat nostrud vol',
                    address: 'Aliquip suscipit dol',
                    country: 'Sunt illum et elige',
                    state: 'Maxime mollit et ea ',
                    zipCode: '58452',
                    phone: '+1 (618) 584-6622',
                },
                paymentInfo: {
                    paymentID: 'test123',
                    status: 'Processed/Paid',
                },
                deliveryStatus: 'Not delivered',
                _id: '60fda99897efed0e6dfa5f21',
                user: '60f1cf2b87c05534ca22d76f',
                orderTotal: 699,
                purchase: [
                    {
                        productID: '60eee5c7f6551d566f992501',
                        brand: 'Adidas',
                        model: 'Yeezy 500 (Enflame)',
                        size: '10.5',
                        img: 'https://res.cloudinary.com/dvoz1ragp/image/upload/v1685824429/street-trend/products/xuuukwjb7j8c7ipm6xaz.webp',
                        price: 300,
                    },
                    {
                        productID: '60ec4b0d182a728b9d356c34',
                        brand: 'Air Jordan',
                        model: 'VII (7) Retro',
                        size: '10.5',
                        img: 'https://res.cloudinary.com/dvoz1ragp/image/upload/v1685824429/street-trend/products/xuuukwjb7j8c7ipm6xaz.webp',
                        price: 399,
                    },
                ],
                paidAt: '2021-07-25T18:12:40.440Z',
            },
            {
                shippingInfo: {
                    firstName: 'John',
                    lastName: 'Doe',
                    email: 'j.doe@gmail.com',
                    city: 'Toronto',
                    address: '781 14 Avenue North ',
                    country: 'Canada',
                    state: 'Ontario',
                    zipCode: 'T3C 0W4',
                    phone: '5876009099',
                },
                paymentInfo: {
                    paymentID: 'test123',
                    status: 'Processed/Paid',
                },
                deliveryStatus: 'Not delivered',
                _id: '60ffa6eb8ebd262bdc6650b2',
                user: '60f2c8dbe45d0d2c2282ff42',
                orderTotal: 510,
                purchase: [
                    {
                        productID: '60eeea4af6551d566f992547',
                        brand: 'Adidas',
                        model: 'NMD_XR1',
                        size: '12',
                        img: 'https://res.cloudinary.com/dvoz1ragp/image/upload/v1685824429/street-trend/products/xuuukwjb7j8c7ipm6xaz.webp',
                        price: 190,
                    },
                    {
                        productID: '60ed779ff236a82619a8002e',
                        brand: 'Adidas',
                        model: 'Pharrell Williams Solar HU Glide',
                        size: '7',
                        img: 'https://res.cloudinary.com/dvoz1ragp/image/upload/v1685824429/street-trend/products/xuuukwjb7j8c7ipm6xaz.webp',
                        price: 320,
                    },
                ],
                paidAt: '2021-07-27T06:25:47.408Z',
            },
        ],
        isLoading: false,
        error: null,
    },

    reviews: {
        productReviews: [],
        allReviews: [],
        isLoading: false,
        isReviewUploaded: false,
        error: null,
    },

    user: {
        isLoading: false,
        isLocationLoaded: false,
        isUploaded: false,
        error: null,
        loggedOut: false,
        sessionExpired: false,
        location: {
            continent: '',
            country: '',
            countryCode: '',
            city: '',
            region: '',
        },
    },
};

export const mockProduct: Product = {
    department: 'men',
    isFeatured: true,
    colors: ['Pearl', 'White', ''],
    size: ['10.5'],
    _id: '60ec4b0d182a728b9d356c34',
    brand: 'New Balance',
    description:
        'The designers of the first 990 were tasked with creating the single best running shoe on the market. The MADE in USA 990v6 embraces this original mandate, with a series of performance-inspired updates. The upper dispenses with the standard midfoot saddle, allowing the pigskin and synthetic overlays to flow from heel to toe across the mesh underlay, for a speedy, streamlined look. While the evolved design marks one of the most dramatic changes from one generation model to the next that the 990 has ever seen, the greatest leap forward occurs on the inside. The addition of FuelCell midsole cushioning means that the evolution of the 990 can be felt as much as it can be seen.',
    images: [
        {
            _id: '647ba3b79e8b118460e42d73',
            public_id: 'street-trend/products/cummusiuf80rolweuzjs',
            url: '/images/990v6_1.webp',
        },
    ],
    model: '990v6',
    price: 399,
    styleCode: '304775-281',
};
